version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes: 
      - .:/var/www:delegated
      - ./tools/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: ./tools/docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    links:
      - db
      - mail
      - redis
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: linkmat
      MYSQL_PASSWORD: linkmat
      MYSQL_DATABASE: linkmat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: = db
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    links:
      - db
    ports:
      - 8888:8080
  node:
    build:
      context: ./tools/docker/node
    command: yarn run watch
    working_dir: /usr/src/app
    user: 1000:1000
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  redis:
    image: redis:5-alpine
volumes:
  db-data:
    driver: local